version: '3.8'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
      interval: 10s
      timeout: 10s
      retries: 3
    command: --default-authentication-plugin=mysql_native_password

  server:
    build: server
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server:/var/express/
      - node_modules-server:/var/express/node_modules/
    env_file:
      - .env

  client_web:
    build: web
    ports:
      - "8082:8082"
    depends_on:
      - server
    volumes:
      - ./web:/var/react
      - node_modules-web:/var/react/node_modules/

  client_mobile:
    build:
      context: mobile
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - ./mobile:/var/react-native/
      - node_modules-mobile:/var/react-native/node_modules/

volumes:
  mysql-volume:
  node_modules-web:
  node_modules-server:
  node_modules-mobile: