version: '3.8'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysql -h localhost -uroot -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"
      interval: 10s
      timeout: 10s
      retries: 3
    command: --default-authentication-plugin=mysql_native_password

  server:
    build: server
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - /var/express/node_modules/
    env_file:
      - .env

  client_web:
    build: web
    ports:
      - "8081:8081"
    depends_on:
      - server
      - client_mobile
    volumes:
      - client-volume:/var/react/apk
      - /var/react/node_modules/

  client_mobile:
    image: alpine:latest
    volumes:
      - client-volume:/var/react-native/build

volumes:
  mysql-volume:
  client-volume: